# Generated by Django 3.2.8 on 2022-03-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_ticket_ticketsnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketsNum',
            new_name='active',
        ),
    ]
