# Generated by Django 3.2.8 on 2022-03-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_rename_ticketsnum_ticket_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='active',
        ),
    ]
